from . import school
from . import  schoolPerson
from . import teach
from . import student
from . import student_result
from . import schoolClass
from . import subject
from . import student_marks
from . import sale
from . import commission_order_line
from . import commission_find
from . import course
from . import course_line
from . import pos_config 
from . import res_location
from . import school_order
from . import school_order_line